version: "3.8"
services:
  web:
    build: .
    image: compose-app
    ports:
      - "5006:5006"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    depends_on:
      - redis  # Ensures Redis starts first
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
volumes:
  redis_data: